name: desafio_bloc_1
description: Desafio FTeam

publish_to: 'none'
version: 1.0.7+8

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  dio: ^4.0.6
  flutter_bloc: ^8.0.1
  flutter_modular: ^5.0.3
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  bloc_test: ^9.0.3
  modular_test: ^2.0.0

flutter:
  uses-material-design: true
