name: desafio_bloc_1
description: Desafio FTeam

publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.0-nullsafety.2
  dio: ^4.0.0
  flutter_bloc: ^7.0.1
  flutter_modular: ^3.4.1+1
  url_launcher: ^6.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.4

flutter:
  uses-material-design: true
