name: desafio_bloc_1
description: Desafio FTeam

publish_to: 'none'
version: 1.0.3+4

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  dio: ^4.0.5
  flutter_bloc: ^8.0.1
  flutter_modular: ^4.5.0
  url_launcher: ^6.0.20
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
