name: desafio_bloc_1
description: Desafio FTeam

publish_to: 'none'
version: 1.0.7+8

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  dio: ^5.10.0
  flutter_bloc: ^9.1.1
  flutter_modular: ^7.1.0
  url_launcher: ^6.3.2
  equatable: ^2.0.5
  widgetbook_annotation: ^3.11.0
  widgetbook: ^3.25.0
  intl: ^0.20.3

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.5
  bloc_test: ^10.0.0
  widgetbook_generator: ^3.24.0
  build_runner: ^2.8.0

flutter:
  uses-material-design: true
