name: desafio_bloc_1
description: Desafio FTeam

publish_to: 'none'
version: 1.0.7+8

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  dio: ^5.1.1
  flutter_bloc: ^8.1.1
  flutter_modular: ^5.0.3
  url_launcher: ^6.1.10
  equatable: ^2.0.5
  uno: ^1.1.6

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  bloc_test: ^9.1.0
  modular_test: ^2.0.0

flutter:
  uses-material-design: true
