name: desafio_bloc_1
description: Desafio FTeam

publish_to: 'none'

version: 1.0.2+3

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.0
  dio: ^4.0.1
  flutter_bloc: ^7.3.1
  flutter_modular: ^4.2.0
  url_launcher: ^6.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0

flutter:
  uses-material-design: true
