name: desafio_bloc_1
description: Desafio FTeam

publish_to: 'none'
version: 1.0.6+7

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  dio: ^4.0.6
  flutter_bloc: ^8.0.1
  flutter_modular: 5.0.0-dev.15
  url_launcher: ^6.1.1
  equatable: ^2.0.3

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  bloc_test: ^9.0.3
  modular_test: 

flutter:
  uses-material-design: true
