name: desafio_bloc_1
description: Desafio FTeam

publish_to: 'none'
version: 1.0.7+8

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  dio: ^5.4.0
  flutter_bloc: ^8.1.3
  flutter_modular: ^5.0.3
  url_launcher: ^6.2.2
  equatable: ^2.0.5
  uno: ^1.1.8
  widgetbook_annotation: ^3.1.0
  widgetbook: ^3.7.1
  intl: ^0.19.0

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.2
  bloc_test: ^9.1.5
  modular_test: ^2.0.0
  widgetbook_generator: ^3.7.0
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
